// A very simple router to send the static files generated by Parcel

const express = require('express')
const fs = require('fs')
const path = require('path')

const loadHtml = name => {
	const read = () =>
		fs.readFileSync(
			path.join(__dirname, 'dist', `${name}.html`),
			'utf-8'
		)

	// Ensure the file exists at startup
	read()

	return (_, res) => res.send(read())
}

const blogPosts = fs.readdirSync(path.join(__dirname, 'source/blog'))
	.filter(x => !x.startsWith('_'))
	.filter(x => x.endsWith('.pug'))
	.map(x => x.slice(0, -('.pug').length))

const makeApp = () => {
	const app = express()

	app.disable('x-powered-by')

	// Ensure that files are loaded on startup

	app.get('/', loadHtml('landing'))
	app.use(express.static('dist', {index: false}))

	app.get('/app/*', loadHtml('app'))
	app.get('/about', loadHtml('about'))
	app.get('/blog', loadHtml('blog'))
	app.get('/docs', loadHtml('docs'))
	app.get('/legal', loadHtml('legal'))
	app.get('/pricing', loadHtml('pricing'))

	blogPosts.forEach(blogPost =>
		app.get(`/blog/${blogPost}`, loadHtml(`blog/${blogPost}`))
	)

	return app
}

if (require.main === module) {
	const port = Number(process.env.PORT)
	const host = process.argv[2] === '--expose' ? '0.0.0.0' : '127.0.0.1'
	makeApp().listen(port, host,
		() => console.log(`Listening on port ${port}`)
	)
}

module.exports = makeApp
